pages = [{"l":"index.html#","e":false,"n":"Aquarium Simulator","t":"Aquarium Simulator","d":"","k":"static"},
{"l":"controller.html#","e":false,"n":"controller","t":"controller","d":"controller","k":"package"},
{"l":"controller/Controller.html#","e":false,"n":"Controller","t":"Controller","d":"controller/Controller","k":"trait"},
{"l":"controller/Controller.html#addFood-995","e":false,"n":"addFood","t":"addFood(food: Food): Unit","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#addInhabitant-fffffc10","e":false,"n":"addInhabitant","t":"addInhabitant[A](inhabitant: A): Unit","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#changeSpeed-fffff7da","e":false,"n":"changeSpeed","t":"changeSpeed(simSpeed: SimulationSpeed): Unit","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#clean-94c","e":false,"n":"clean","t":"clean(): Unit","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#currentIteration-0","e":false,"n":"currentIteration","t":"currentIteration: Int","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#deleteFood-995","e":false,"n":"deleteFood","t":"deleteFood(food: Food): Unit","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#getAllAlgae-fffff84b","e":false,"n":"getAllAlgae","t":"getAllAlgae(iteration: Int): List[Algae]","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#getAllFish-fffff84b","e":false,"n":"getAllFish","t":"getAllFish(iteration: Int): List[Fish]","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#getAquarium-0","e":false,"n":"getAquarium","t":"getAquarium: Aquarium","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#getCurrentChronicle-0","e":false,"n":"getCurrentChronicle","t":"getCurrentChronicle: Chronicle","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#getPopulationTrend-0","e":false,"n":"getPopulationTrend","t":"getPopulationTrend: List[(Int, Int, Int)]","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#getSpeed-0","e":false,"n":"getSpeed","t":"getSpeed: SimulationSpeed","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#isRunning-0","e":false,"n":"isRunning","t":"isRunning: Boolean","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#pauseSimulation-94c","e":false,"n":"pauseSimulation","t":"pauseSimulation(): Unit","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#removeInhabitant-fffffc10","e":false,"n":"removeInhabitant","t":"removeInhabitant[A](inhabitant: A): Unit","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#startSimulation-fffff7da","e":false,"n":"startSimulation","t":"startSimulation(simSpeed: SimulationSpeed): Unit","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#stopSimulation-94c","e":false,"n":"stopSimulation","t":"stopSimulation(): Unit","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#updateBrightness-fffff7a5","e":false,"n":"updateBrightness","t":"updateBrightness(brightness: Double): Unit","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#updateOxygenation-fffff7a5","e":false,"n":"updateOxygenation","t":"updateOxygenation(oxygenation: Double): Unit","d":"controller/Controller","k":"def"},
{"l":"controller/Controller.html#updateTemperature-fffff7a5","e":false,"n":"updateTemperature","t":"updateTemperature(temperature: Double): Unit","d":"controller/Controller","k":"def"},
{"l":"controller/ControllerComponent.html#","e":false,"n":"ControllerComponent","t":"ControllerComponent","d":"controller/ControllerComponent","k":"trait"},
{"l":"controller/ControllerComponent.html#given_ControllerRequirements-0","e":false,"n":"given_ControllerRequirements","t":"given_ControllerRequirements: ControllerRequirements","d":"controller/ControllerComponent","k":"given"},
{"l":"controller/ControllerComponent$ControllerImpl.html#","e":false,"n":"ControllerImpl","t":"ControllerImpl extends Controller","d":"controller/ControllerComponent$ControllerImpl","k":"class"},
{"l":"controller/ControllerComponent$ControllerImpl.html#simEngine-0","e":false,"n":"simEngine","t":"simEngine: SimulationEngine","d":"controller/ControllerComponent$ControllerImpl","k":"val"},
{"l":"controller/SimulationEngine.html#","e":false,"n":"SimulationEngine","t":"SimulationEngine","d":"controller/SimulationEngine","k":"trait"},
{"l":"controller/SimulationEngine.html#changeSpeed-fffff7da","e":false,"n":"changeSpeed","t":"changeSpeed(simSpeed: SimulationSpeed): Unit","d":"controller/SimulationEngine","k":"def"},
{"l":"controller/SimulationEngine.html#getAquarium-ffffff29","e":false,"n":"getAquarium","t":"getAquarium(): Aquarium","d":"controller/SimulationEngine","k":"def"},
{"l":"controller/SimulationEngine.html#getIterations-ffffff27","e":false,"n":"getIterations","t":"getIterations(): Int","d":"controller/SimulationEngine","k":"def"},
{"l":"controller/SimulationEngine.html#getSpeed-80e","e":false,"n":"getSpeed","t":"getSpeed(): SimulationSpeed","d":"controller/SimulationEngine","k":"def"},
{"l":"controller/SimulationEngine.html#isRunning-fffff760","e":false,"n":"isRunning","t":"isRunning(): Boolean","d":"controller/SimulationEngine","k":"def"},
{"l":"controller/SimulationEngine.html#pause-94c","e":false,"n":"pause","t":"pause(): Unit","d":"controller/SimulationEngine","k":"def"},
{"l":"controller/SimulationEngine.html#start-fffff7da","e":false,"n":"start","t":"start(simSpeed: SimulationSpeed): Unit","d":"controller/SimulationEngine","k":"def"},
{"l":"controller/SimulationEngine.html#stop-94c","e":false,"n":"stop","t":"stop(): Unit","d":"controller/SimulationEngine","k":"def"},
{"l":"controller/SimulationEngine$.html#","e":false,"n":"SimulationEngine","t":"SimulationEngine","d":"controller/SimulationEngine$","k":"object"},
{"l":"controller/SimulationEngine$.html#apply-468","e":false,"n":"apply","t":"apply(aquarium: Aquarium)(using context: ControllerRequirements): SimulationEngine","d":"controller/SimulationEngine$","k":"def"},
{"l":"controller/SimulationSpeed.html#","e":false,"n":"SimulationSpeed","t":"SimulationSpeed","d":"controller/SimulationSpeed","k":"enum"},
{"l":"controller/SimulationSpeed.html#HALT-0","e":false,"n":"HALT","t":"HALT extends SimulationSpeed","d":"controller/SimulationSpeed","k":"case"},
{"l":"controller/SimulationSpeed.html#SLOW-0","e":false,"n":"SLOW","t":"SLOW extends SimulationSpeed","d":"controller/SimulationSpeed","k":"case"},
{"l":"controller/SimulationSpeed.html#NORMAL-0","e":false,"n":"NORMAL","t":"NORMAL extends SimulationSpeed","d":"controller/SimulationSpeed","k":"case"},
{"l":"controller/SimulationSpeed.html#FAST-0","e":false,"n":"FAST","t":"FAST extends SimulationSpeed","d":"controller/SimulationSpeed","k":"case"},
{"l":"controller/SimulationSpeed.html#STOP-0","e":false,"n":"STOP","t":"STOP extends SimulationSpeed","d":"controller/SimulationSpeed","k":"case"},
{"l":"model.html#","e":false,"n":"model","t":"model","d":"model","k":"package"},
{"l":"model/Algae.html#","e":false,"n":"Algae","t":"Algae(base: Double, height: Int) extends Entity","d":"model/Algae","k":"class"},
{"l":"model/Algae.html#impurityShift-0","e":false,"n":"impurityShift","t":"impurityShift: Double","d":"model/Algae","k":"val"},
{"l":"model/Algae.html#oxygenShift-0","e":false,"n":"oxygenShift","t":"oxygenShift: Double","d":"model/Algae","k":"val"},
{"l":"model/Algae.html#phShift-0","e":false,"n":"phShift","t":"phShift: Double","d":"model/Algae","k":"val"},
{"l":"model/Algae.html#position-0","e":false,"n":"position","t":"position: (Double, Double)","d":"model/Algae","k":"val"},
{"l":"model/Algae.html#size-0","e":false,"n":"size","t":"size: (Double, Double)","d":"model/Algae","k":"val"},
{"l":"model/Algae$.html#","e":false,"n":"Algae","t":"Algae","d":"model/Algae$","k":"object"},
{"l":"model/Algae$.html#DEFAULT_HEIGHT-0","e":false,"n":"DEFAULT_HEIGHT","t":"DEFAULT_HEIGHT: Int","d":"model/Algae$","k":"val"},
{"l":"model/Algae$.html#LOWER_BRIGHTNESS_LEVEL-0","e":false,"n":"LOWER_BRIGHTNESS_LEVEL","t":"LOWER_BRIGHTNESS_LEVEL: Int","d":"model/Algae$","k":"val"},
{"l":"model/Algae$.html#MAX_GROWTH-0","e":false,"n":"MAX_GROWTH","t":"MAX_GROWTH: Int","d":"model/Algae$","k":"val"},
{"l":"model/Algae$.html#MAX_HEIGHT-0","e":false,"n":"MAX_HEIGHT","t":"MAX_HEIGHT: Int","d":"model/Algae$","k":"val"},
{"l":"model/Algae$.html#MIN_GROWTH-0","e":false,"n":"MIN_GROWTH","t":"MIN_GROWTH: Int","d":"model/Algae$","k":"val"},
{"l":"model/Algae$.html#NUTRITION_AMOUNT-0","e":false,"n":"NUTRITION_AMOUNT","t":"NUTRITION_AMOUNT: Int","d":"model/Algae$","k":"val"},
{"l":"model/Algae$.html#OXYGEN_MULTIPLIER-0","e":false,"n":"OXYGEN_MULTIPLIER","t":"OXYGEN_MULTIPLIER: Double","d":"model/Algae$","k":"val"},
{"l":"model/Algae$.html#PH_DIVISOR-0","e":false,"n":"PH_DIVISOR","t":"PH_DIVISOR: Double","d":"model/Algae$","k":"val"},
{"l":"model/Entity.html#","e":false,"n":"Entity","t":"Entity","d":"model/Entity","k":"trait"},
{"l":"model/Entity.html#collidesWith-fffff5f8","e":false,"n":"collidesWith","t":"collidesWith(other: Entity): Boolean","d":"model/Entity","k":"def"},
{"l":"model/Entity.html#impurityShift-0","e":false,"n":"impurityShift","t":"impurityShift: Double","d":"model/Entity","k":"val"},
{"l":"model/Entity.html#oxygenShift-0","e":false,"n":"oxygenShift","t":"oxygenShift: Double","d":"model/Entity","k":"val"},
{"l":"model/Entity.html#phShift-0","e":false,"n":"phShift","t":"phShift: Double","d":"model/Entity","k":"val"},
{"l":"model/Entity.html#position-0","e":false,"n":"position","t":"position: (Double, Double)","d":"model/Entity","k":"val"},
{"l":"model/Entity.html#size-0","e":false,"n":"size","t":"size: (Double, Double)","d":"model/Entity","k":"val"},
{"l":"model/FeedingType.html#","e":false,"n":"FeedingType","t":"FeedingType","d":"model/FeedingType","k":"enum"},
{"l":"model/FeedingType.html#HERBIVOROUS-0","e":false,"n":"HERBIVOROUS","t":"HERBIVOROUS extends FeedingType","d":"model/FeedingType","k":"case"},
{"l":"model/FeedingType.html#CARNIVOROUS-0","e":false,"n":"CARNIVOROUS","t":"CARNIVOROUS extends FeedingType","d":"model/FeedingType","k":"case"},
{"l":"model/FeedingType.html#OMNIVOROUS-0","e":false,"n":"OMNIVOROUS","t":"OMNIVOROUS extends FeedingType","d":"model/FeedingType","k":"case"},
{"l":"model/Model.html#","e":false,"n":"Model","t":"Model","d":"model/Model","k":"trait"},
{"l":"model/Model.html#addChronicleEvent-571","e":false,"n":"addChronicleEvent","t":"addChronicleEvent(event: String): Unit","d":"model/Model","k":"def"},
{"l":"model/Model.html#addUserInteraction-c9d","e":false,"n":"addUserInteraction","t":"addUserInteraction(interaction: Aquarium => Aquarium): Unit","d":"model/Model","k":"def"},
{"l":"model/Model.html#chronicle-0","e":false,"n":"chronicle","t":"chronicle: Chronicle","d":"model/Model","k":"def"},
{"l":"model/Model.html#getDatabase-0","e":false,"n":"getDatabase","t":"getDatabase: PrologEngine","d":"model/Model","k":"def"},
{"l":"model/Model.html#initializeAquarium-2","e":false,"n":"initializeAquarium","t":"initializeAquarium(herbivorousFishNumber: Int, carnivorousFishNumber: Int, algaeNumber: Int): Aquarium","d":"model/Model","k":"def"},
{"l":"model/Model.html#saveAquarium-9ea","e":false,"n":"saveAquarium","t":"saveAquarium(aquarium: Aquarium, iteration: Int): Unit","d":"model/Model","k":"def"},
{"l":"model/Model.html#step-1e0","e":false,"n":"step","t":"step(currentAquarium: Aquarium): Aquarium","d":"model/Model","k":"def"},
{"l":"model/ModelComponent.html#","e":false,"n":"ModelComponent","t":"ModelComponent","d":"model/ModelComponent","k":"trait"},
{"l":"model/ModelComponent$ModelImpl.html#","e":false,"n":"ModelImpl","t":"ModelImpl extends Model","d":"model/ModelComponent$ModelImpl","k":"class"},
{"l":"model/aquarium.html#","e":false,"n":"model.aquarium","t":"model.aquarium","d":"model/aquarium","k":"package"},
{"l":"model/aquarium/Aquarium.html#","e":false,"n":"Aquarium","t":"Aquarium(aquariumState: AquariumState, population: Population, availableFood: Set[Food]) extends AvailableFood with UpdateAvailableFood","d":"model/aquarium/Aquarium","k":"class"},
{"l":"model/aquarium/Aquarium$.html#","e":false,"n":"Aquarium","t":"Aquarium","d":"model/aquarium/Aquarium$","k":"object"},
{"l":"model/aquarium/Aquarium$.html#apply-2","e":false,"n":"apply","t":"apply(herbivorousFishNumber: Int, carnivorousFishNumber: Int, algaeNumber: Int): Aquarium","d":"model/aquarium/Aquarium$","k":"def"},
{"l":"model/aquarium/AquariumDimensions$.html#","e":false,"n":"AquariumDimensions","t":"AquariumDimensions","d":"model/aquarium/AquariumDimensions$","k":"object"},
{"l":"model/aquarium/AquariumDimensions$.html#HEIGHT-0","e":false,"n":"HEIGHT","t":"HEIGHT: Int","d":"model/aquarium/AquariumDimensions$","k":"val"},
{"l":"model/aquarium/AquariumDimensions$.html#WIDTH-0","e":false,"n":"WIDTH","t":"WIDTH: Int","d":"model/aquarium/AquariumDimensions$","k":"val"},
{"l":"model/aquarium/AquariumParametersLimits$.html#","e":false,"n":"AquariumParametersLimits","t":"AquariumParametersLimits","d":"model/aquarium/AquariumParametersLimits$","k":"object"},
{"l":"model/aquarium/AquariumParametersLimits$.html#ALGAE_MAX-0","e":false,"n":"ALGAE_MAX","t":"ALGAE_MAX: Int","d":"model/aquarium/AquariumParametersLimits$","k":"val"},
{"l":"model/aquarium/AquariumParametersLimits$.html#BRIGHTNESS_MAX-0","e":false,"n":"BRIGHTNESS_MAX","t":"BRIGHTNESS_MAX: Int","d":"model/aquarium/AquariumParametersLimits$","k":"val"},
{"l":"model/aquarium/AquariumParametersLimits$.html#BRIGHTNESS_MIN-0","e":false,"n":"BRIGHTNESS_MIN","t":"BRIGHTNESS_MIN: Int","d":"model/aquarium/AquariumParametersLimits$","k":"val"},
{"l":"model/aquarium/AquariumParametersLimits$.html#FISH_MAX-0","e":false,"n":"FISH_MAX","t":"FISH_MAX: Int","d":"model/aquarium/AquariumParametersLimits$","k":"val"},
{"l":"model/aquarium/AquariumParametersLimits$.html#IMPURITY_MAX-0","e":false,"n":"IMPURITY_MAX","t":"IMPURITY_MAX: Int","d":"model/aquarium/AquariumParametersLimits$","k":"val"},
{"l":"model/aquarium/AquariumParametersLimits$.html#IMPURITY_MIN-0","e":false,"n":"IMPURITY_MIN","t":"IMPURITY_MIN: Int","d":"model/aquarium/AquariumParametersLimits$","k":"val"},
{"l":"model/aquarium/AquariumParametersLimits$.html#OXYGENATION_MAX-0","e":false,"n":"OXYGENATION_MAX","t":"OXYGENATION_MAX: Int","d":"model/aquarium/AquariumParametersLimits$","k":"val"},
{"l":"model/aquarium/AquariumParametersLimits$.html#OXYGENATION_MIN-0","e":false,"n":"OXYGENATION_MIN","t":"OXYGENATION_MIN: Int","d":"model/aquarium/AquariumParametersLimits$","k":"val"},
{"l":"model/aquarium/AquariumParametersLimits$.html#PH_MAX-0","e":false,"n":"PH_MAX","t":"PH_MAX: Double","d":"model/aquarium/AquariumParametersLimits$","k":"val"},
{"l":"model/aquarium/AquariumParametersLimits$.html#PH_MIN-0","e":false,"n":"PH_MIN","t":"PH_MIN: Double","d":"model/aquarium/AquariumParametersLimits$","k":"val"},
{"l":"model/aquarium/AquariumParametersLimits$.html#TEMPERATURE_MAX-0","e":false,"n":"TEMPERATURE_MAX","t":"TEMPERATURE_MAX: Int","d":"model/aquarium/AquariumParametersLimits$","k":"val"},
{"l":"model/aquarium/AquariumParametersLimits$.html#TEMPERATURE_MIN-0","e":false,"n":"TEMPERATURE_MIN","t":"TEMPERATURE_MIN: Int","d":"model/aquarium/AquariumParametersLimits$","k":"val"},
{"l":"model/aquarium/AquariumState.html#","e":false,"n":"AquariumState","t":"AquariumState(temperature: Double, brightness: Double, ph: Double, impurity: Double, oxygenation: Double) extends UpdateAquariumState","d":"model/aquarium/AquariumState","k":"class"},
{"l":"model/aquarium/AvailableFood.html#","e":false,"n":"AvailableFood","t":"AvailableFood","d":"model/aquarium/AvailableFood","k":"trait"},
{"l":"model/aquarium/AvailableFood.html#availableFood-0","e":false,"n":"availableFood","t":"availableFood: Set[Food]","d":"model/aquarium/AvailableFood","k":"val"},
{"l":"model/aquarium/AvailableFood.html#carnivorousFood-0","e":false,"n":"carnivorousFood","t":"carnivorousFood: Set[Food]","d":"model/aquarium/AvailableFood","k":"def"},
{"l":"model/aquarium/AvailableFood.html#herbivorousFood-0","e":false,"n":"herbivorousFood","t":"herbivorousFood: Set[Food]","d":"model/aquarium/AvailableFood","k":"def"},
{"l":"model/aquarium/FishTypes.html#","e":false,"n":"FishTypes","t":"FishTypes","d":"model/aquarium/FishTypes","k":"trait"},
{"l":"model/aquarium/FishTypes.html#carnivorous-0","e":false,"n":"carnivorous","t":"carnivorous: Set[Fish]","d":"model/aquarium/FishTypes","k":"def"},
{"l":"model/aquarium/FishTypes.html#fish-0","e":false,"n":"fish","t":"fish: Set[Fish]","d":"model/aquarium/FishTypes","k":"val"},
{"l":"model/aquarium/FishTypes.html#herbivorous-0","e":false,"n":"herbivorous","t":"herbivorous: Set[Fish]","d":"model/aquarium/FishTypes","k":"def"},
{"l":"model/aquarium/InitializeAquarium$.html#","e":false,"n":"InitializeAquarium","t":"InitializeAquarium","d":"model/aquarium/InitializeAquarium$","k":"object"},
{"l":"model/aquarium/InitializeAquarium$.html#ALGAE-0","e":false,"n":"ALGAE","t":"ALGAE: Int","d":"model/aquarium/InitializeAquarium$","k":"val"},
{"l":"model/aquarium/InitializeAquarium$.html#BRIGHTNESS-0","e":false,"n":"BRIGHTNESS","t":"BRIGHTNESS: Double","d":"model/aquarium/InitializeAquarium$","k":"val"},
{"l":"model/aquarium/InitializeAquarium$.html#CARNIVOROUS_FISH-0","e":false,"n":"CARNIVOROUS_FISH","t":"CARNIVOROUS_FISH: Int","d":"model/aquarium/InitializeAquarium$","k":"val"},
{"l":"model/aquarium/InitializeAquarium$.html#HERBIVOROUS_FISH-0","e":false,"n":"HERBIVOROUS_FISH","t":"HERBIVOROUS_FISH: Int","d":"model/aquarium/InitializeAquarium$","k":"val"},
{"l":"model/aquarium/InitializeAquarium$.html#IMPURITY-0","e":false,"n":"IMPURITY","t":"IMPURITY: Double","d":"model/aquarium/InitializeAquarium$","k":"val"},
{"l":"model/aquarium/InitializeAquarium$.html#OXYGENATION-0","e":false,"n":"OXYGENATION","t":"OXYGENATION: Double","d":"model/aquarium/InitializeAquarium$","k":"val"},
{"l":"model/aquarium/InitializeAquarium$.html#PH-0","e":false,"n":"PH","t":"PH: Double","d":"model/aquarium/InitializeAquarium$","k":"val"},
{"l":"model/aquarium/InitializeAquarium$.html#TEMPERATURE-0","e":false,"n":"TEMPERATURE","t":"TEMPERATURE: Double","d":"model/aquarium/InitializeAquarium$","k":"val"},
{"l":"model/aquarium/Population.html#","e":false,"n":"Population","t":"Population(fish: Set[Fish], algae: Set[Algae]) extends FishTypes with UpdatePopulation","d":"model/aquarium/Population","k":"class"},
{"l":"model/aquarium/Population$.html#","e":false,"n":"Population","t":"Population","d":"model/aquarium/Population$","k":"object"},
{"l":"model/aquarium/Population$.html#apply-5c4","e":false,"n":"apply","t":"apply(herbivorousFishNumber: Int, carnivorousFishNumber: Int, algaeNumber: Int): Population","d":"model/aquarium/Population$","k":"def"},
{"l":"model/aquarium/Population$.html#randomBase-999","e":false,"n":"randomBase","t":"randomBase(): Double","d":"model/aquarium/Population$","k":"def"},
{"l":"model/aquarium/Population$.html#randomPosition-ffffff32","e":false,"n":"randomPosition","t":"randomPosition(): (Double, Double)","d":"model/aquarium/Population$","k":"def"},
{"l":"model/aquarium/Population$.html#randomSpeed-ffffff32","e":false,"n":"randomSpeed","t":"randomSpeed(): (Double, Double)","d":"model/aquarium/Population$","k":"def"},
{"l":"model/aquarium/UpdateAquariumState.html#","e":false,"n":"UpdateAquariumState","t":"UpdateAquariumState","d":"model/aquarium/UpdateAquariumState","k":"trait"},
{"l":"model/aquarium/UpdateAquariumState.html#updateBrightness-101","e":false,"n":"updateBrightness","t":"updateBrightness(newBrightness: Double): AquariumState","d":"model/aquarium/UpdateAquariumState","k":"def"},
{"l":"model/aquarium/UpdateAquariumState.html#updateImpurity-101","e":false,"n":"updateImpurity","t":"updateImpurity(newImpurity: Double): AquariumState","d":"model/aquarium/UpdateAquariumState","k":"def"},
{"l":"model/aquarium/UpdateAquariumState.html#updateOxygenation-101","e":false,"n":"updateOxygenation","t":"updateOxygenation(newOxygenation: Double): AquariumState","d":"model/aquarium/UpdateAquariumState","k":"def"},
{"l":"model/aquarium/UpdateAquariumState.html#updatePh-101","e":false,"n":"updatePh","t":"updatePh(newPh: Double): AquariumState","d":"model/aquarium/UpdateAquariumState","k":"def"},
{"l":"model/aquarium/UpdateAquariumState.html#updateTemperature-101","e":false,"n":"updateTemperature","t":"updateTemperature(newTemperature: Double): AquariumState","d":"model/aquarium/UpdateAquariumState","k":"def"},
{"l":"model/aquarium/UpdateAvailableFood.html#","e":false,"n":"UpdateAvailableFood","t":"UpdateAvailableFood","d":"model/aquarium/UpdateAvailableFood","k":"trait"},
{"l":"model/aquarium/UpdateAvailableFood.html#addFood-d80","e":false,"n":"addFood","t":"addFood(food: Food): Aquarium","d":"model/aquarium/UpdateAvailableFood","k":"def"},
{"l":"model/aquarium/UpdateAvailableFood.html#deleteFood-d80","e":false,"n":"deleteFood","t":"deleteFood(food: Food): Aquarium","d":"model/aquarium/UpdateAvailableFood","k":"def"},
{"l":"model/aquarium/UpdatePopulation.html#","e":false,"n":"UpdatePopulation","t":"UpdatePopulation","d":"model/aquarium/UpdatePopulation","k":"trait"},
{"l":"model/aquarium/UpdatePopulation.html#addInhabitant-3e7","e":false,"n":"addInhabitant","t":"addInhabitant[A](newInhabitant: A): Population","d":"model/aquarium/UpdatePopulation","k":"def"},
{"l":"model/aquarium/UpdatePopulation.html#removeInhabitant-3e7","e":false,"n":"removeInhabitant","t":"removeInhabitant[A](removedInhabitant: A): Population","d":"model/aquarium/UpdatePopulation","k":"def"},
{"l":"model/chronicle.html#","e":false,"n":"model.chronicle","t":"model.chronicle","d":"model/chronicle","k":"package"},
{"l":"model/chronicle/Chronicle.html#","e":false,"n":"Chronicle","t":"Chronicle(events: List[String]) extends UpdateChronicle","d":"model/chronicle/Chronicle","k":"class"},
{"l":"model/chronicle/Events$.html#","e":false,"n":"Events","t":"Events","d":"model/chronicle/Events$","k":"object"},
{"l":"model/chronicle/Events$.html#ADDED_ENTITY-c40","e":false,"n":"ADDED_ENTITY","t":"ADDED_ENTITY[A]: A => String","d":"model/chronicle/Events$","k":"def"},
{"l":"model/chronicle/Events$.html#CHANGED_SPEED-0","e":false,"n":"CHANGED_SPEED","t":"CHANGED_SPEED: String => String","d":"model/chronicle/Events$","k":"val"},
{"l":"model/chronicle/Events$.html#CLEAN_AQUARIUM-0","e":false,"n":"CLEAN_AQUARIUM","t":"CLEAN_AQUARIUM: String","d":"model/chronicle/Events$","k":"val"},
{"l":"model/chronicle/Events$.html#ENTITY_DEATH-c40","e":false,"n":"ENTITY_DEATH","t":"ENTITY_DEATH[A]: A => String","d":"model/chronicle/Events$","k":"def"},
{"l":"model/chronicle/Events$.html#FISH_ATE_ENTITY-c41","e":false,"n":"FISH_ATE_ENTITY","t":"FISH_ATE_ENTITY[A]: (String, A) => String","d":"model/chronicle/Events$","k":"def"},
{"l":"model/chronicle/Events$.html#FISH_BIRTH-0","e":false,"n":"FISH_BIRTH","t":"FISH_BIRTH: String => String","d":"model/chronicle/Events$","k":"val"},
{"l":"model/chronicle/Events$.html#REMOVED_ENTITY-c40","e":false,"n":"REMOVED_ENTITY","t":"REMOVED_ENTITY[A]: A => String","d":"model/chronicle/Events$","k":"def"},
{"l":"model/chronicle/Events$.html#UPDATED_AQUARIUM_STATE_PARAMETER-0","e":false,"n":"UPDATED_AQUARIUM_STATE_PARAMETER","t":"UPDATED_AQUARIUM_STATE_PARAMETER: (Double, String, String) => String","d":"model/chronicle/Events$","k":"val"},
{"l":"model/chronicle/UpdateChronicle.html#","e":false,"n":"UpdateChronicle","t":"UpdateChronicle","d":"model/chronicle/UpdateChronicle","k":"trait"},
{"l":"model/chronicle/UpdateChronicle.html#addEvent-fffffa66","e":false,"n":"addEvent","t":"addEvent(event: String): Chronicle","d":"model/chronicle/UpdateChronicle","k":"def"},
{"l":"model/db.html#","e":false,"n":"model.db","t":"model.db","d":"model/db","k":"package"},
{"l":"model/db/AlgaeSerializer$.html#","e":false,"n":"AlgaeSerializer","t":"AlgaeSerializer extends Serializer[Algae]","d":"model/db/AlgaeSerializer$","k":"object"},
{"l":"model/db/AlgaeSerializer$.html#deserialize-fffffc16","e":false,"n":"deserialize","t":"deserialize(info: String): Algae","d":"model/db/AlgaeSerializer$","k":"def"},
{"l":"model/db/AlgaeSerializer$.html#serialize-fffff851","e":false,"n":"serialize","t":"serialize(algae: Algae, iteration: Int): String","d":"model/db/AlgaeSerializer$","k":"def"},
{"l":"model/db/FishSerializer$.html#","e":false,"n":"FishSerializer","t":"FishSerializer extends Serializer[Fish]","d":"model/db/FishSerializer$","k":"object"},
{"l":"model/db/FishSerializer$.html#deserialize-fffff6c4","e":false,"n":"deserialize","t":"deserialize(info: String): Fish","d":"model/db/FishSerializer$","k":"def"},
{"l":"model/db/FishSerializer$.html#serialize-fffff7e3","e":false,"n":"serialize","t":"serialize(fish: Fish, iteration: Int): String","d":"model/db/FishSerializer$","k":"def"},
{"l":"model/db/FoodSerializer$.html#","e":false,"n":"FoodSerializer","t":"FoodSerializer extends Serializer[Food]","d":"model/db/FoodSerializer$","k":"object"},
{"l":"model/db/PrologEngine.html#","e":false,"n":"PrologEngine","t":"PrologEngine","d":"model/db/PrologEngine","k":"trait"},
{"l":"model/db/PrologEngine.html#clear-94c","e":false,"n":"clear","t":"clear(): Unit","d":"model/db/PrologEngine","k":"def"},
{"l":"model/db/PrologEngine.html#getAllAlgae-fffff84b","e":false,"n":"getAllAlgae","t":"getAllAlgae(iteration: Int): List[Algae]","d":"model/db/PrologEngine","k":"def"},
{"l":"model/db/PrologEngine.html#getAllCarnivorousFish-fffff84b","e":false,"n":"getAllCarnivorousFish","t":"getAllCarnivorousFish(iteration: Int): List[Fish]","d":"model/db/PrologEngine","k":"def"},
{"l":"model/db/PrologEngine.html#getAllCarnivorousFood-0","e":false,"n":"getAllCarnivorousFood","t":"getAllCarnivorousFood: List[Food]","d":"model/db/PrologEngine","k":"def"},
{"l":"model/db/PrologEngine.html#getAllFish-fffff84b","e":false,"n":"getAllFish","t":"getAllFish(iteration: Int): List[Fish]","d":"model/db/PrologEngine","k":"def"},
{"l":"model/db/PrologEngine.html#getAllFood-0","e":false,"n":"getAllFood","t":"getAllFood: List[Food]","d":"model/db/PrologEngine","k":"def"},
{"l":"model/db/PrologEngine.html#getAllHerbivorousFish-fffff84b","e":false,"n":"getAllHerbivorousFish","t":"getAllHerbivorousFish(iteration: Int): List[Fish]","d":"model/db/PrologEngine","k":"def"},
{"l":"model/db/PrologEngine.html#getAllHerbivorousFood-0","e":false,"n":"getAllHerbivorousFood","t":"getAllHerbivorousFood: List[Food]","d":"model/db/PrologEngine","k":"def"},
{"l":"model/db/PrologEngine.html#saveAlgae-fffffc38","e":false,"n":"saveAlgae","t":"saveAlgae(algae: Algae, iteration: Int): Unit","d":"model/db/PrologEngine","k":"def"},
{"l":"model/db/PrologEngine.html#saveFish-14a","e":false,"n":"saveFish","t":"saveFish(fish: Fish, iteration: Int): Unit","d":"model/db/PrologEngine","k":"def"},
{"l":"model/db/PrologEngine.html#saveFood-995","e":false,"n":"saveFood","t":"saveFood(food: Food): Unit","d":"model/db/PrologEngine","k":"def"},
{"l":"model/db/PrologEngine$.html#","e":false,"n":"PrologEngine","t":"PrologEngine extends PrologEngine","d":"model/db/PrologEngine$","k":"object"},
{"l":"model/db/Serializer.html#","e":false,"n":"Serializer","t":"Serializer[T]","d":"model/db/Serializer","k":"trait"},
{"l":"model/db/Serializer.html#deserialize-fffff5f8","e":false,"n":"deserialize","t":"deserialize(obj: String): T","d":"model/db/Serializer","k":"def"},
{"l":"model/db/Serializer.html#serialize-fffff959","e":false,"n":"serialize","t":"serialize(obj: T, iteration: Int): String","d":"model/db/Serializer","k":"def"},
{"l":"model/fish.html#","e":false,"n":"model.fish","t":"model.fish","d":"model/fish","k":"package"},
{"l":"model/fish/Fish.html#","e":false,"n":"Fish","t":"Fish(name: String, satiety: Int, age: Int, speed: (Double, Double), size: (Double, Double), position: (Double, Double), feedingType: FeedingType, reproductionFactor: Int) extends Entity with UpdateFish","d":"model/fish/Fish","k":"class"},
{"l":"model/fish/Fish.html#impurityShift-0","e":false,"n":"impurityShift","t":"impurityShift: Double","d":"model/fish/Fish","k":"val"},
{"l":"model/fish/Fish.html#isAlive-0","e":false,"n":"isAlive","t":"isAlive: Boolean","d":"model/fish/Fish","k":"def"},
{"l":"model/fish/Fish.html#oxygenShift-0","e":false,"n":"oxygenShift","t":"oxygenShift: Double","d":"model/fish/Fish","k":"val"},
{"l":"model/fish/Fish.html#phShift-0","e":false,"n":"phShift","t":"phShift: Double","d":"model/fish/Fish","k":"val"},
{"l":"model/fish/Fish$.html#","e":false,"n":"Fish","t":"Fish","d":"model/fish/Fish$","k":"object"},
{"l":"model/fish/Fish$.html#AGE_FISH-0","e":false,"n":"AGE_FISH","t":"AGE_FISH: Int","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#AGE_SHIFT-0","e":false,"n":"AGE_SHIFT","t":"AGE_SHIFT: Int","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#IMPURITY_SHIFT_CONSTANT-0","e":false,"n":"IMPURITY_SHIFT_CONSTANT","t":"IMPURITY_SHIFT_CONSTANT: Double","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#MAX_HEIGHT-0","e":false,"n":"MAX_HEIGHT","t":"MAX_HEIGHT: Double","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#MAX_REPRODUCTION_FACTOR-0","e":false,"n":"MAX_REPRODUCTION_FACTOR","t":"MAX_REPRODUCTION_FACTOR: Int","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#MAX_SATIETY-0","e":false,"n":"MAX_SATIETY","t":"MAX_SATIETY: Int","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#MAX_SIZE-0","e":false,"n":"MAX_SIZE","t":"MAX_SIZE: Double","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#MAX_SPEED-0","e":false,"n":"MAX_SPEED","t":"MAX_SPEED: Int","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#MAX_WIDTH-0","e":false,"n":"MAX_WIDTH","t":"MAX_WIDTH: Double","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#MEAT_AMOUNT-0","e":false,"n":"MEAT_AMOUNT","t":"MEAT_AMOUNT: Double","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#MIN_SIZE-0","e":false,"n":"MIN_SIZE","t":"MIN_SIZE: Double","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#MIN_SPEED-0","e":false,"n":"MIN_SPEED","t":"MIN_SPEED: Int","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#OXYGEN_SHIFT_CONSTANT-0","e":false,"n":"OXYGEN_SHIFT_CONSTANT","t":"OXYGEN_SHIFT_CONSTANT: Double","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#PH_SHIFT_CONSTANT-0","e":false,"n":"PH_SHIFT_CONSTANT","t":"PH_SHIFT_CONSTANT: Double","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#REPRODUCTION_COST-0","e":false,"n":"REPRODUCTION_COST","t":"REPRODUCTION_COST: Int","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#REPRODUCTION_FACTOR_SHIFT-0","e":false,"n":"REPRODUCTION_FACTOR_SHIFT","t":"REPRODUCTION_FACTOR_SHIFT: Int","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#SATIETY_SHIFT-0","e":false,"n":"SATIETY_SHIFT","t":"SATIETY_SHIFT: Int","d":"model/fish/Fish$","k":"val"},
{"l":"model/fish/Fish$.html#getAndIncrementN-ffffff27","e":false,"n":"getAndIncrementN","t":"getAndIncrementN(): Int","d":"model/fish/Fish$","k":"def"},
{"l":"model/fish/Fish$.html#n-0","e":false,"n":"n","t":"n: Int","d":"model/fish/Fish$","k":"var"},
{"l":"model/fish/UpdateFish.html#","e":false,"n":"UpdateFish","t":"UpdateFish","d":"model/fish/UpdateFish","k":"trait"},
{"l":"model/fish/UpdateFish.html#move-510","e":false,"n":"move","t":"move(speedMultiplier: Double): Fish","d":"model/fish/UpdateFish","k":"def"},
{"l":"model/fish/UpdateFish.html#updateReproductionFactor-1c2","e":false,"n":"updateReproductionFactor","t":"updateReproductionFactor(newReproductionFactor: Int): Fish","d":"model/fish/UpdateFish","k":"def"},
{"l":"model/fish/UpdateFish.html#updateSatiety-1c2","e":false,"n":"updateSatiety","t":"updateSatiety(newSatiety: Int): Fish","d":"model/fish/UpdateFish","k":"def"},
{"l":"model/food.html#","e":false,"n":"model.food","t":"model.food","d":"model/food","k":"package"},
{"l":"model/food/Food$.html#","e":false,"n":"Food","t":"Food","d":"model/food/Food$","k":"object"},
{"l":"model/food/Food$.html#IMPURITY_CONSTANT-0","e":false,"n":"IMPURITY_CONSTANT","t":"IMPURITY_CONSTANT: Double","d":"model/food/Food$","k":"val"},
{"l":"model/food/Food$.html#MAX_NUTRITION_AMOUNT-0","e":false,"n":"MAX_NUTRITION_AMOUNT","t":"MAX_NUTRITION_AMOUNT: Int","d":"model/food/Food$","k":"val"},
{"l":"model/food/Food$.html#MIN_NUTRITION_AMOUNT-0","e":false,"n":"MIN_NUTRITION_AMOUNT","t":"MIN_NUTRITION_AMOUNT: Int","d":"model/food/Food$","k":"val"},
{"l":"model/food/Food$.html#SPEED-0","e":false,"n":"SPEED","t":"SPEED: (Double, Double)","d":"model/food/Food$","k":"val"},
{"l":"model/food/Food$.html#SPEED_MULTIPLIER-0","e":false,"n":"SPEED_MULTIPLIER","t":"SPEED_MULTIPLIER: Double","d":"model/food/Food$","k":"val"},
{"l":"model/food/Food.html#","e":false,"n":"Food","t":"Food(position: (Double, Double), nutritionAmount: Int, feedingType: FeedingType) extends Entity","d":"model/food/Food","k":"class"},
{"l":"model/food/Food.html#impurityShift-0","e":false,"n":"impurityShift","t":"impurityShift: Double","d":"model/food/Food","k":"val"},
{"l":"model/food/Food.html#oxygenShift-0","e":false,"n":"oxygenShift","t":"oxygenShift: Double","d":"model/food/Food","k":"val"},
{"l":"model/food/Food.html#phShift-0","e":false,"n":"phShift","t":"phShift: Double","d":"model/food/Food","k":"val"},
{"l":"model/food/Food.html#size-0","e":false,"n":"size","t":"size: (Double, Double)","d":"model/food/Food","k":"val"},
{"l":"model/food/UpdateFood.html#","e":false,"n":"UpdateFood","t":"UpdateFood","d":"model/food/UpdateFood","k":"trait"},
{"l":"model/food/UpdateFood.html#calculatePosition-ffffff32","e":false,"n":"calculatePosition","t":"calculatePosition(): (Double, Double)","d":"model/food/UpdateFood","k":"def"},
{"l":"model/food/UpdateFood.html#move-8d0","e":false,"n":"move","t":"move(speedMultiplier: Double): Food","d":"model/food/UpdateFood","k":"def"},
{"l":"model/food/UpdateFood.html#updatePosition-fffffe17","e":false,"n":"updatePosition","t":"updatePosition(newPosition: (Double, Double)): Food","d":"model/food/UpdateFood","k":"def"},
{"l":"model/food/UpdateFood$.html#","e":false,"n":"UpdateFood","t":"UpdateFood","d":"model/food/UpdateFood$","k":"object"},
{"l":"model/food/UpdateFood$.html#apply-fffff3c9","e":false,"n":"apply","t":"apply(food: Food): UpdateFood","d":"model/food/UpdateFood$","k":"def"},
{"l":"model/interaction.html#","e":false,"n":"model.interaction","t":"model.interaction","d":"model/interaction","k":"package"},
{"l":"model/interaction/DeathProbabilityAlgae$.html#","e":false,"n":"DeathProbabilityAlgae","t":"DeathProbabilityAlgae","d":"model/interaction/DeathProbabilityAlgae$","k":"object"},
{"l":"model/interaction/DeathProbabilityAlgae$.html#LACK_OF_BRIGHTNESS-0","e":false,"n":"LACK_OF_BRIGHTNESS","t":"LACK_OF_BRIGHTNESS: Double => Double","d":"model/interaction/DeathProbabilityAlgae$","k":"val"},
{"l":"model/interaction/DeathProbabilityAlgae$.html#MAX_BRIGHTNESS_LEVEL_PROB_INTERVAL-0","e":false,"n":"MAX_BRIGHTNESS_LEVEL_PROB_INTERVAL","t":"MAX_BRIGHTNESS_LEVEL_PROB_INTERVAL: Int","d":"model/interaction/DeathProbabilityAlgae$","k":"val"},
{"l":"model/interaction/DeathProbabilityAlgae$.html#PROB_MIN_BRIGHTNESS-0","e":false,"n":"PROB_MIN_BRIGHTNESS","t":"PROB_MIN_BRIGHTNESS: Int","d":"model/interaction/DeathProbabilityAlgae$","k":"val"},
{"l":"model/interaction/DeathProbabilityFish$.html#","e":false,"n":"DeathProbabilityFish","t":"DeathProbabilityFish","d":"model/interaction/DeathProbabilityFish$","k":"object"},
{"l":"model/interaction/DeathProbabilityFish$.html#FISH_AGE-0","e":false,"n":"FISH_AGE","t":"FISH_AGE: Double => Double","d":"model/interaction/DeathProbabilityFish$","k":"val"},
{"l":"model/interaction/DeathProbabilityFish$.html#LOW_OXYGENATION-0","e":false,"n":"LOW_OXYGENATION","t":"LOW_OXYGENATION: Double => Double","d":"model/interaction/DeathProbabilityFish$","k":"val"},
{"l":"model/interaction/DeathProbabilityFish$.html#MAX_AGE_FISH-0","e":false,"n":"MAX_AGE_FISH","t":"MAX_AGE_FISH: Int","d":"model/interaction/DeathProbabilityFish$","k":"val"},
{"l":"model/interaction/DeathProbabilityFish$.html#MAX_INTERVAL_TOO_LOW_OXYGENATION-0","e":false,"n":"MAX_INTERVAL_TOO_LOW_OXYGENATION","t":"MAX_INTERVAL_TOO_LOW_OXYGENATION: Int","d":"model/interaction/DeathProbabilityFish$","k":"val"},
{"l":"model/interaction/DeathProbabilityFish$.html#MAX_SAFE_PH-0","e":false,"n":"MAX_SAFE_PH","t":"MAX_SAFE_PH: Double","d":"model/interaction/DeathProbabilityFish$","k":"val"},
{"l":"model/interaction/DeathProbabilityFish$.html#MIN_AGE_FISH-0","e":false,"n":"MIN_AGE_FISH","t":"MIN_AGE_FISH: Int","d":"model/interaction/DeathProbabilityFish$","k":"val"},
{"l":"model/interaction/DeathProbabilityFish$.html#MIN_SAFE_PH-0","e":false,"n":"MIN_SAFE_PH","t":"MIN_SAFE_PH: Double","d":"model/interaction/DeathProbabilityFish$","k":"val"},
{"l":"model/interaction/DeathProbabilityFish$.html#PROB_AGE-0","e":false,"n":"PROB_AGE","t":"PROB_AGE: Int","d":"model/interaction/DeathProbabilityFish$","k":"val"},
{"l":"model/interaction/DeathProbabilityFish$.html#PROB_OXYGEN-0","e":false,"n":"PROB_OXYGEN","t":"PROB_OXYGEN: Int","d":"model/interaction/DeathProbabilityFish$","k":"val"},
{"l":"model/interaction/DeathProbabilityFish$.html#PROB_PH-0","e":false,"n":"PROB_PH","t":"PROB_PH: Int","d":"model/interaction/DeathProbabilityFish$","k":"val"},
{"l":"model/interaction/DeathProbabilityFish$.html#TOO_HIGH_PH-0","e":false,"n":"TOO_HIGH_PH","t":"TOO_HIGH_PH: Double => Double","d":"model/interaction/DeathProbabilityFish$","k":"val"},
{"l":"model/interaction/DeathProbabilityFish$.html#TOO_LOW_PH-0","e":false,"n":"TOO_LOW_PH","t":"TOO_LOW_PH: Double => Double","d":"model/interaction/DeathProbabilityFish$","k":"val"},
{"l":"model/interaction/Interaction.html#","e":false,"n":"Interaction","t":"Interaction[A]","d":"model/interaction/Interaction","k":"trait"},
{"l":"model/interaction/Interaction.html#update-993","e":false,"n":"update","t":"update(): A","d":"model/interaction/Interaction","k":"def"},
{"l":"model/interaction/Interaction$.html#","e":false,"n":"Interaction","t":"Interaction","d":"model/interaction/Interaction$","k":"object"},
{"l":"model/interaction/Interaction$.html#apply-fffffb2e","e":false,"n":"apply","t":"apply(algae: Algae, aquariumState: AquariumState): Interaction[Option[Algae]]","d":"model/interaction/Interaction$","k":"def"},
{"l":"model/interaction/Interaction$.html#apply-901","e":false,"n":"apply","t":"apply(aquariumState: AquariumState, entity: Entity): Interaction[AquariumState]","d":"model/interaction/Interaction$","k":"def"},
{"l":"model/interaction/Interaction$.html#apply-fffff2c0","e":false,"n":"apply","t":"apply(fish: Fish, aquariumState: AquariumState): Interaction[Option[Fish]]","d":"model/interaction/Interaction$","k":"def"},
{"l":"model/interaction/Interaction$.html#apply-fffff95f","e":false,"n":"apply","t":"apply(fish: Fish, algae: Algae): Interaction[(Fish, Option[Algae])]","d":"model/interaction/Interaction$","k":"def"},
{"l":"model/interaction/Interaction$.html#apply-fffff371","e":false,"n":"apply","t":"apply(fish1: Fish, fish2: Fish): Interaction[(Option[Fish], Option[Fish], Option[Fish])]","d":"model/interaction/Interaction$","k":"def"},
{"l":"model/interaction/Interaction$.html#apply-fffff7b1","e":false,"n":"apply","t":"apply(fish: Fish, food: Food): Interaction[(Fish, Option[Food])]","d":"model/interaction/Interaction$","k":"def"},
{"l":"model/interaction/MultiplierVelocityFish$.html#","e":false,"n":"MultiplierVelocityFish","t":"MultiplierVelocityFish","d":"model/interaction/MultiplierVelocityFish$","k":"object"},
{"l":"model/interaction/MultiplierVelocityFish$.html#MAX_SPEED_IMPURITY-0","e":false,"n":"MAX_SPEED_IMPURITY","t":"MAX_SPEED_IMPURITY: Int","d":"model/interaction/MultiplierVelocityFish$","k":"val"},
{"l":"model/interaction/MultiplierVelocityFish$.html#MAX_SPEED_TEMPERATURE-0","e":false,"n":"MAX_SPEED_TEMPERATURE","t":"MAX_SPEED_TEMPERATURE: Int","d":"model/interaction/MultiplierVelocityFish$","k":"val"},
{"l":"model/interaction/MultiplierVelocityFish$.html#SPEED_MULTIPLIER_IMPURITY-0","e":false,"n":"SPEED_MULTIPLIER_IMPURITY","t":"SPEED_MULTIPLIER_IMPURITY: Double => Double","d":"model/interaction/MultiplierVelocityFish$","k":"val"},
{"l":"model/interaction/MultiplierVelocityFish$.html#SPEED_MULTIPLIER_TEMPERATURE-0","e":false,"n":"SPEED_MULTIPLIER_TEMPERATURE","t":"SPEED_MULTIPLIER_TEMPERATURE: Double => Double","d":"model/interaction/MultiplierVelocityFish$","k":"val"},
{"l":"mvc.html#","e":false,"n":"mvc","t":"mvc","d":"mvc","k":"package"},
{"l":"mvc/ControllerModule$.html#","e":false,"n":"ControllerModule","t":"ControllerModule","d":"mvc/ControllerModule$","k":"object"},
{"l":"mvc/ControllerModule$.html#ControllerRequirements-0","e":false,"n":"ControllerRequirements","t":"ControllerRequirements = Provider & Provider","d":"mvc/ControllerModule$","k":"type"},
{"l":"mvc/ControllerModule$$Interface.html#","e":false,"n":"Interface","t":"Interface extends Provider with ControllerComponent","d":"mvc/ControllerModule$$Interface","k":"trait"},
{"l":"mvc/ControllerModule$$Provider.html#","e":false,"n":"Provider","t":"Provider","d":"mvc/ControllerModule$$Provider","k":"trait"},
{"l":"mvc/ControllerModule$$Provider.html#controller-0","e":false,"n":"controller","t":"controller: Controller","d":"mvc/ControllerModule$$Provider","k":"val"},
{"l":"mvc/MVC$.html#","e":false,"n":"MVC","t":"MVC extends MVCTrait with JFXApp3","d":"mvc/MVC$","k":"object"},
{"l":"mvc/MVC$.html#controller-0","e":false,"n":"controller","t":"controller: Controller","d":"mvc/MVC$","k":"val"},
{"l":"mvc/MVC$.html#model-0","e":false,"n":"model","t":"model: Model","d":"mvc/MVC$","k":"val"},
{"l":"mvc/MVC$.html#view-0","e":false,"n":"view","t":"view: View","d":"mvc/MVC$","k":"val"},
{"l":"mvc/MVCTrait.html#","e":false,"n":"MVCTrait","t":"MVCTrait extends Interface with Interface with Interface","d":"mvc/MVCTrait","k":"trait"},
{"l":"mvc/ModelModule$.html#","e":false,"n":"ModelModule","t":"ModelModule","d":"mvc/ModelModule$","k":"object"},
{"l":"mvc/ModelModule$$Interface.html#","e":false,"n":"Interface","t":"Interface extends Provider with ModelComponent","d":"mvc/ModelModule$$Interface","k":"trait"},
{"l":"mvc/ModelModule$$Provider.html#","e":false,"n":"Provider","t":"Provider","d":"mvc/ModelModule$$Provider","k":"trait"},
{"l":"mvc/ModelModule$$Provider.html#model-0","e":false,"n":"model","t":"model: Model","d":"mvc/ModelModule$$Provider","k":"val"},
{"l":"mvc/ViewModule$.html#","e":false,"n":"ViewModule","t":"ViewModule","d":"mvc/ViewModule$","k":"object"},
{"l":"mvc/ViewModule$.html#ViewRequirements-0","e":false,"n":"ViewRequirements","t":"ViewRequirements = Provider","d":"mvc/ViewModule$","k":"type"},
{"l":"mvc/ViewModule$$Interface.html#","e":false,"n":"Interface","t":"Interface extends Provider with ViewComponent","d":"mvc/ViewModule$$Interface","k":"trait"},
{"l":"mvc/ViewModule$$Provider.html#","e":false,"n":"Provider","t":"Provider","d":"mvc/ViewModule$$Provider","k":"trait"},
{"l":"mvc/ViewModule$$Provider.html#view-0","e":false,"n":"view","t":"view: View","d":"mvc/ViewModule$$Provider","k":"val"},
{"l":"view.html#","e":false,"n":"view","t":"view","d":"view","k":"package"},
{"l":"view/GUI.html#","e":false,"n":"GUI","t":"GUI","d":"view/GUI","k":"trait"},
{"l":"view/GUI.html#start-fffff6e4","e":false,"n":"start","t":"start(stage: Stage): Unit","d":"view/GUI","k":"def"},
{"l":"view/GUI.html#updateSliders-f63","e":false,"n":"updateSliders","t":"updateSliders(temperature: Number, brightness: Number, oxygenation: Number): Unit","d":"view/GUI","k":"def"},
{"l":"view/GUI$.html#","e":false,"n":"GUI","t":"GUI","d":"view/GUI$","k":"object"},
{"l":"view/GUI$.html#start-fffff6e4","e":false,"n":"start","t":"start(stage: Stage): Unit","d":"view/GUI$","k":"def"},
{"l":"view/GUI$.html#updateSliders-aa9","e":false,"n":"updateSliders","t":"updateSliders(oxygenation: Number): Unit","d":"view/GUI$","k":"def"},
{"l":"view/View.html#","e":false,"n":"View","t":"View","d":"view/View","k":"trait"},
{"l":"view/View.html#renderSimulation-935","e":false,"n":"renderSimulation","t":"renderSimulation(aquarium: Aquarium): Unit","d":"view/View","k":"def"},
{"l":"view/View.html#show-fffff6e4","e":false,"n":"show","t":"show(stage: Stage): Unit","d":"view/View","k":"def"},
{"l":"view/ViewComponent.html#","e":false,"n":"ViewComponent","t":"ViewComponent","d":"view/ViewComponent","k":"trait"},
{"l":"view/ViewComponent.html#given_ViewRequirements-0","e":false,"n":"given_ViewRequirements","t":"given_ViewRequirements: ViewRequirements","d":"view/ViewComponent","k":"given"},
{"l":"view/ViewComponent$FakeViewImpl.html#","e":false,"n":"FakeViewImpl","t":"FakeViewImpl extends View","d":"view/ViewComponent$FakeViewImpl","k":"class"},
{"l":"view/ViewComponent$ViewImpl.html#","e":false,"n":"ViewImpl","t":"ViewImpl extends View","d":"view/ViewComponent$ViewImpl","k":"class"},
{"l":"view/ViewComponent$ViewImpl.html#renderSimulation-935","e":false,"n":"renderSimulation","t":"renderSimulation(aquarium: Aquarium): Unit","d":"view/ViewComponent$ViewImpl","k":"def"},
{"l":"view/ViewComponent$ViewImpl.html#show-fffff6e4","e":false,"n":"show","t":"show(stage: Stage): Unit","d":"view/ViewComponent$ViewImpl","k":"def"},
{"l":"view/utils.html#","e":false,"n":"view.utils","t":"view.utils","d":"view/utils","k":"package"},
{"l":"view/utils/AquariumFonts$.html#","e":false,"n":"AquariumFonts","t":"AquariumFonts","d":"view/utils/AquariumFonts$","k":"object"},
{"l":"view/utils/AquariumFonts$.html#bold-a9f","e":false,"n":"bold","t":"bold(size: Double): Font","d":"view/utils/AquariumFonts$","k":"def"},
{"l":"view/utils/AquariumFonts$.html#fontFamily-0","e":false,"n":"fontFamily","t":"fontFamily: String","d":"view/utils/AquariumFonts$","k":"val"},
{"l":"view/utils/AquariumFonts$.html#normal-a9f","e":false,"n":"normal","t":"normal(size: Double): Font","d":"view/utils/AquariumFonts$","k":"def"},
{"l":"view/utils/IconButton$.html#","e":false,"n":"IconButton","t":"IconButton","d":"view/utils/IconButton$","k":"object"},
{"l":"view/utils/IconButton$.html#setImage-f42","e":false,"n":"setImage","t":"setImage(button: IconButton, iconPath: String, buttonHeight: Int, buttonWidth: Int): Unit","d":"view/utils/IconButton$","k":"def"},
{"l":"view/utils/IconButton.html#","e":false,"n":"IconButton","t":"IconButton(val iconPath: String, val buttonHeight: Int, val buttonWidth: Int) extends Button","d":"view/utils/IconButton","k":"class"},
{"l":"view/utils/IconButton.html#buttonHeight-0","e":false,"n":"buttonHeight","t":"buttonHeight: Int","d":"view/utils/IconButton","k":"val"},
{"l":"view/utils/IconButton.html#buttonWidth-0","e":false,"n":"buttonWidth","t":"buttonWidth: Int","d":"view/utils/IconButton","k":"val"},
{"l":"view/utils/IconButton.html#iconPath-0","e":false,"n":"iconPath","t":"iconPath: String","d":"view/utils/IconButton","k":"val"},
{"l":"view/utils/IconLabel$.html#","e":false,"n":"IconLabel","t":"IconLabel","d":"view/utils/IconLabel$","k":"object"},
{"l":"view/utils/IconLabel$.html#apply-9c1","e":false,"n":"apply","t":"apply(iconPath: String, tooltipMessage: String): Label","d":"view/utils/IconLabel$","k":"def"},
{"l":"view/widgets.html#","e":false,"n":"view.widgets","t":"view.widgets","d":"view/widgets","k":"package"},
{"l":"view/widgets/BottomBar$.html#","e":false,"n":"BottomBar","t":"BottomBar","d":"view/widgets/BottomBar$","k":"object"},
{"l":"view/widgets/BottomBar$.html#addFishButton-0","e":false,"n":"addFishButton","t":"addFishButton: BottomBarButton","d":"view/widgets/BottomBar$","k":"val"},
{"l":"view/widgets/BottomBar$.html#bottomBar-0","e":false,"n":"bottomBar","t":"bottomBar: TilePane","d":"view/widgets/BottomBar$","k":"val"},
{"l":"view/widgets/BottomBar$.html#changeSpeedButton-0","e":false,"n":"changeSpeedButton","t":"changeSpeedButton: BottomBarButton","d":"view/widgets/BottomBar$","k":"val"},
{"l":"view/widgets/BottomBar$.html#cleanButton-0","e":false,"n":"cleanButton","t":"cleanButton: BottomBarButton","d":"view/widgets/BottomBar$","k":"val"},
{"l":"view/widgets/BottomBar$.html#foodButton-0","e":false,"n":"foodButton","t":"foodButton: BottomBarButton","d":"view/widgets/BottomBar$","k":"val"},
{"l":"view/widgets/BottomBar$.html#playButton-0","e":false,"n":"playButton","t":"playButton: BottomBarButton","d":"view/widgets/BottomBar$","k":"val"},
{"l":"view/widgets/BottomBar$.html#speedBeforeStop-0","e":false,"n":"speedBeforeStop","t":"speedBeforeStop: SimulationSpeed","d":"view/widgets/BottomBar$","k":"var"},
{"l":"view/widgets/BottomBarButton$.html#","e":false,"n":"BottomBarButton","t":"BottomBarButton","d":"view/widgets/BottomBarButton$","k":"object"},
{"l":"view/widgets/BottomBarButton$.html#DEFAULT_HEIGHT-0","e":false,"n":"DEFAULT_HEIGHT","t":"DEFAULT_HEIGHT: Int","d":"view/widgets/BottomBarButton$","k":"val"},
{"l":"view/widgets/BottomBarButton$.html#DEFAULT_WIDTH-0","e":false,"n":"DEFAULT_WIDTH","t":"DEFAULT_WIDTH: Int","d":"view/widgets/BottomBarButton$","k":"val"},
{"l":"view/widgets/BottomBarButton.html#","e":false,"n":"BottomBarButton","t":"BottomBarButton(val iconPath: String) extends IconButton","d":"view/widgets/BottomBarButton","k":"class"},
{"l":"view/widgets/BottomBarButton.html#iconPath-0","e":false,"n":"iconPath","t":"iconPath: String","d":"view/widgets/BottomBarButton","k":"val"},
{"l":"view/widgets/Chronicle$.html#","e":false,"n":"Chronicle","t":"Chronicle","d":"view/widgets/Chronicle$","k":"object"},
{"l":"view/widgets/Chronicle$.html#chronicle-0","e":false,"n":"chronicle","t":"chronicle: BorderPane","d":"view/widgets/Chronicle$","k":"val"},
{"l":"view/widgets/Chronicle$.html#list-0","e":false,"n":"list","t":"list: ListView[String]","d":"view/widgets/Chronicle$","k":"var"},
{"l":"view/widgets/Chronicle$.html#update-fffff303","e":false,"n":"update","t":"update(context: ViewRequirements): Unit","d":"view/widgets/Chronicle$","k":"def"},
{"l":"view/widgets/InfoCell.html#","e":false,"n":"InfoCell","t":"InfoCell extends BorderPane","d":"view/widgets/InfoCell","k":"trait"},
{"l":"view/widgets/InfoCell.html#update-fffff7a5","e":false,"n":"update","t":"update(newValue: Double): Unit","d":"view/widgets/InfoCell","k":"def"},
{"l":"view/widgets/InfoCell$.html#","e":false,"n":"InfoCell","t":"InfoCell","d":"view/widgets/InfoCell$","k":"object"},
{"l":"view/widgets/InfoCell$.html#apply-fffff0d5","e":false,"n":"apply","t":"apply(title: String, initialValue: Double, unit: String): InfoCell","d":"view/widgets/InfoCell$","k":"def"},
{"l":"view/widgets/InfoPane.html#","e":false,"n":"InfoPane","t":"InfoPane","d":"view/widgets/InfoPane","k":"trait"},
{"l":"view/widgets/InfoPane.html#updateInfo-935","e":false,"n":"updateInfo","t":"updateInfo(newAquarium: Aquarium): Unit","d":"view/widgets/InfoPane","k":"def"},
{"l":"view/widgets/InfoPane$.html#","e":false,"n":"InfoPane","t":"InfoPane","d":"view/widgets/InfoPane$","k":"object"},
{"l":"view/widgets/InfoPane$.html#pane-0","e":false,"n":"pane","t":"pane: BorderPane","d":"view/widgets/InfoPane$","k":"val"},
{"l":"view/widgets/InfoPane$.html#updateInfo-935","e":false,"n":"updateInfo","t":"updateInfo(newAquarium: Aquarium): Unit","d":"view/widgets/InfoPane$","k":"def"},
{"l":"view/widgets/SimulationViewer$.html#","e":false,"n":"SimulationViewer","t":"SimulationViewer","d":"view/widgets/SimulationViewer$","k":"object"},
{"l":"view/widgets/SimulationViewer$.html#canvasPane-0","e":false,"n":"canvasPane","t":"canvasPane: BorderPane","d":"view/widgets/SimulationViewer$","k":"val"},
{"l":"view/widgets/SimulationViewer$.html#findEntityClicked-a6f","e":false,"n":"findEntityClicked","t":"findEntityClicked(coordinates: (Double, Double)): Option[Entity]","d":"view/widgets/SimulationViewer$","k":"def"},
{"l":"view/widgets/SimulationViewer$.html#renderSimulation-935","e":false,"n":"renderSimulation","t":"renderSimulation(aquarium: Aquarium): Unit","d":"view/widgets/SimulationViewer$","k":"def"},
{"l":"view/widgets/StatisticsView.html#","e":false,"n":"StatisticsView","t":"StatisticsView extends Stage","d":"view/widgets/StatisticsView","k":"class"},
{"l":"view/widgets/download.html#","e":false,"n":"view.widgets.download","t":"view.widgets.download","d":"view/widgets/download","k":"package"},
{"l":"view/widgets/download/DownloadCSV$.html#","e":false,"n":"DownloadCSV","t":"DownloadCSV","d":"view/widgets/download/DownloadCSV$","k":"object"},
{"l":"view/widgets/download/DownloadCSV$.html#apply-571","e":false,"n":"apply","t":"apply(path: String): Unit","d":"view/widgets/download/DownloadCSV$","k":"def"},
{"l":"view/widgets/download/DownloadJSON$.html#","e":false,"n":"DownloadJSON","t":"DownloadJSON","d":"view/widgets/download/DownloadJSON$","k":"object"},
{"l":"view/widgets/download/DownloadJSON$.html#apply-571","e":false,"n":"apply","t":"apply(path: String): Unit","d":"view/widgets/download/DownloadJSON$","k":"def"},
{"l":"view/widgets/slider.html#","e":false,"n":"view.widgets.slider","t":"view.widgets.slider","d":"view/widgets/slider","k":"package"},
{"l":"view/widgets/slider/BrightnessSlider.html#","e":false,"n":"BrightnessSlider","t":"BrightnessSlider extends BorderPane","d":"view/widgets/slider/BrightnessSlider","k":"trait"},
{"l":"view/widgets/slider/BrightnessSlider.html#update-aa9","e":false,"n":"update","t":"update(newValue: Number): Unit","d":"view/widgets/slider/BrightnessSlider","k":"def"},
{"l":"view/widgets/slider/BrightnessSlider$.html#","e":false,"n":"BrightnessSlider","t":"BrightnessSlider","d":"view/widgets/slider/BrightnessSlider$","k":"object"},
{"l":"view/widgets/slider/BrightnessSlider$.html#apply-fffffc97","e":false,"n":"apply","t":"apply(): BrightnessSlider","d":"view/widgets/slider/BrightnessSlider$","k":"def"},
{"l":"view/widgets/slider/OxygenationSlider.html#","e":false,"n":"OxygenationSlider","t":"OxygenationSlider extends BorderPane","d":"view/widgets/slider/OxygenationSlider","k":"trait"},
{"l":"view/widgets/slider/OxygenationSlider.html#update-aa9","e":false,"n":"update","t":"update(newValue: Number): Unit","d":"view/widgets/slider/OxygenationSlider","k":"def"},
{"l":"view/widgets/slider/OxygenationSlider$.html#","e":false,"n":"OxygenationSlider","t":"OxygenationSlider","d":"view/widgets/slider/OxygenationSlider$","k":"object"},
{"l":"view/widgets/slider/OxygenationSlider$.html#apply-331","e":false,"n":"apply","t":"apply(): OxygenationSlider","d":"view/widgets/slider/OxygenationSlider$","k":"def"},
{"l":"view/widgets/slider/SliderUtils$.html#","e":false,"n":"SliderUtils","t":"SliderUtils","d":"view/widgets/slider/SliderUtils$","k":"object"},
{"l":"view/widgets/slider/SliderUtils$.html#getTooltip-b58","e":false,"n":"getTooltip","t":"getTooltip(value: Number, unit: String): Tooltip","d":"view/widgets/slider/SliderUtils$","k":"def"},
{"l":"view/widgets/slider/TemperatureSlider.html#","e":false,"n":"TemperatureSlider","t":"TemperatureSlider extends BorderPane","d":"view/widgets/slider/TemperatureSlider","k":"trait"},
{"l":"view/widgets/slider/TemperatureSlider.html#update-aa9","e":false,"n":"update","t":"update(newValue: Number): Unit","d":"view/widgets/slider/TemperatureSlider","k":"def"},
{"l":"view/widgets/slider/TemperatureSlider$.html#","e":false,"n":"TemperatureSlider","t":"TemperatureSlider","d":"view/widgets/slider/TemperatureSlider$","k":"object"},
{"l":"view/widgets/slider/TemperatureSlider$.html#apply-810","e":false,"n":"apply","t":"apply(): TemperatureSlider","d":"view/widgets/slider/TemperatureSlider$","k":"def"}];