name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Aquarium Simulator build]
    types: [completed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: openjdk@1.17

      - name: Generate Fat Jar
        run: sbt assembly && mkdir downloads && mv ./target/scala-3.1.3/Aquarium*.jar downloads/
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload artifacts to release
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads