name: GitHub Pages Deploy Action

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: openjdk@1.17

      - uses: avinal/github-pages-deploy-action@0.9
        with:
          GITHUB_TOKEN: ${{ github.token }}
          LANGUAGE: "scala"
          MAKE_COMMAND: "sbt doc"
          PAGES_BRANCH: "gh-pages"
          BUILD_FROM: "master"
          DOCS_FOLDER: "./target/scala-3.1.3/api"
