name: GitHub Pages Deploy Action

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: openjdk@1.17
      
      - name: Generate documentation
        run: sbt doc

      - name: Publish documentation to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: ./target/scala-3.1.3/api
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
